[workspace]
members = ["contracts/*", "packages/*", "utils/*"]
exclude = ["tests"]
default-members = [
    "packages/*",
    "contracts/cw-placeholder",
    "contracts/factory",
    "contracts/gauge-adapter",
    "contracts/multi-hop",
    "contracts/nominated-trader",
    "contracts/pair",
    "contracts/pair_lsd",
    "contracts/splitter",
    "contracts/stake",
    "utils/*",
]

[workspace.package]
version = "2.2.0"
edition = "2021"
license = "GPL 3.0"
repository = "https://github.com/cosmorama/wynddex"

[workspace.dependencies]
anyhow = "1"
cw2 = { path = "../cw-minus/packages/cw2" }
cosmwasm-schema = "3.0.4"
cosmwasm-std = "3.0.4"
cw-controllers = { path = "../cw-minus/packages/controllers" }
cw-multi-test = { version = "3.0.0", features = ["staking"], git = "https://github.com/permissionlessweb/cw-multi-test" }
cw-placeholder = { path = "./contracts/cw-placeholder" }
cw-storage-plus = "3.0.1"
cw-utils  = { path = "../cw-minus/packages/cw-utils" }
cw20 = { path = "../cw-plus/packages/cw20" }
cw20-base = { path = "../cw-plus/contracts/cw20-base" }
derivative = "2.2"
itertools = "0.10"
lp-converter = { path = "./contracts/lp-converter", features = ["library"] }
proptest = "1.0"
semver = "1"
serde = { version = "1", default-features = false, features = ["derive"] }
test-case = "2.2.1"
thiserror = "1"
uint = "0.9"
wynd-lsd-hub = { path = "../wynd-lsd/contracts/lsd-hub", features = ["library"] }
wyndex = { path = "./packages/wyndex", default-features = false }
wyndex-factory = { path = "./contracts/factory" }
wyndex-multi-hop = { path = "./contracts/multi-hop" }
wyndex-pair = { path = "./contracts/pair" }
wyndex-pair-lsd = { path = "./contracts/pair_lsd" }
wyndex-stake = { path = "./contracts/stake" }
wyndex-test-helpers = { path = "./packages/wyndex-test-helpers" }

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
strip = true

[profile.release.package.wyndex-factory]
codegen-units = 1
incremental = false

[profile.release.package.wyndex-multi-hop]
codegen-units = 1
incremental = false

[profile.release.package.wyndex-pair]
codegen-units = 1
incremental = false

[profile.release.package.wyndex-pair-lsd]
codegen-units = 1
incremental = false

[profile.release.package.wyndex-stake]
codegen-units = 1
incremental = false

[profile.release.package.cw-placeholder]
codegen-units = 1
incremental = false

[profile.release.package.gauge-adapter]
codegen-units = 1
incremental = false

[profile.release.package.junoswap-staking]
codegen-units = 1
incremental = false

[profile.release.package.raw-migration]
codegen-units = 1
incremental = false

[profile.release.package.lp-converter]
codegen-units = 1
incremental = false

[profile.release.package.cw-splitter]
codegen-units = 1
incremental = false

[profile.release.package.nominated-trader]
codegen-units = 1
incremental = false
