[workspace]
members = ["contracts/*", "packages/*", "utils/*"]
exclude = ["tests"]
default-members = [
    "packages/*",
    "contracts/cw-placeholder",
    "contracts/factory",
    "contracts/gauge-adapter",
    "contracts/multi-hop",
    "contracts/nominated-trader",
    "contracts/pair",
    "contracts/pair_lsd",
    "contracts/splitter",
    "contracts/stake",
    "utils/*",
]

[workspace.package]
version = "2.2.0"
edition = "2021"
license = "GPL 3.0"
repository = "https://github.com/cosmorama/wynddex"

[workspace.dependencies]
anyhow = "1"
cw2 = { git = "https://github.com/permissionlessweb/cw-minus", branch = "main" }
cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cw-controllers = { git = "https://github.com/permissionlessweb/cw-minus", branch = "main" }
cw-multi-test = { git = "https://github.com/permissionlessweb/cw-multi-test", branch = "mvp" }
cw-placeholder = { path = "./contracts/cw-placeholder", features = ["library"] }
cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "mvp" }
cw-utils = { git = "https://github.com/permissionlessweb/cw-minus", branch = "main" }
cw20 = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
cw20-base = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
derivative = "2.2"
itertools = "0.10"
lp-converter = { path = "./contracts/lp-converter", features = ["library"] }
proptest = "1.0"
semver = "1"
serde = { version = "1", default-features = false, features = ["derive"] }
test-case = "2.2.1"
thiserror = "1"
uint = "0.9"
wynd-lsd-hub = { git = "https://github.com/permissionlessweb/wynd-lsd", branch = "cw3", features = ["library"] }
wyndex = { path = "./packages/wyndex" }
wyndex-factory = { path = "./contracts/factory", features = ["library"] }
wyndex-multi-hop = { path = "./contracts/multi-hop", features = ["library"] }
wyndex-pair = { path = "./contracts/pair", features = ["library"] }
wyndex-pair-lsd = { path = "./contracts/pair_lsd", features = ["library"] }
wyndex-stake = { path = "./contracts/stake", features = ["library"] }
wyndex-test-helpers = { path = "./packages/wyndex-test-helpers" }

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
strip = true

[profile.release.package.wyndex-factory]
codegen-units = 1
incremental = false

[profile.release.package.wyndex-multi-hop]
codegen-units = 1
incremental = false

[profile.release.package.wyndex-pair]
codegen-units = 1
incremental = false

[profile.release.package.wyndex-pair-lsd]
codegen-units = 1
incremental = false

[profile.release.package.wyndex-stake]
codegen-units = 1
incremental = false

[profile.release.package.cw-placeholder]
codegen-units = 1
incremental = false

[profile.release.package.gauge-adapter]
codegen-units = 1
incremental = false

[profile.release.package.junoswap-staking]
codegen-units = 1
incremental = false

[profile.release.package.raw-migration]
codegen-units = 1
incremental = false

[profile.release.package.lp-converter]
codegen-units = 1
incremental = false

[profile.release.package.cw-splitter]
codegen-units = 1
incremental = false

[profile.release.package.nominated-trader]
codegen-units = 1
incremental = false
